[project]
name = "meshbbs"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "meshtastic>=2.7.8",
    "peewee>=4.0.4",
]

[project.scripts]
bbs = "meshbbs.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

